import path from 'node:path';

import { defineConfig, mergeConfig } from 'vitest/config';
import viteConfig from './vite.config';

export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: 'jsdom',
      setupFiles: './setup.jsdom.ts',
      exclude: [
        '**/node_modules/**',
        '**/dist/**',
        '**/cypress/**',
        '**/.{idea,git,cache,output,temp}/**',
        '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
        '**/electron/**',
        '**/html/**',
        '**/out/**',
        '**/mock/**',
        '**/src/libs/**',
        '**/src/**/*.backup.ts',
        '**/src/**/*.lib.ts',
        '**/src/**/*.backup.tsx',
        '**/src/**/*.lib.tsx',
        '**/src/**/*.backup',
        '**/src/**/*.lib',
        '**/src/**/lib/**',
        '**/src/**/*.ts',
        '**/src/**/*.js',
        '**/src/**/*.png',
        '**/src/**/*.svg',
        '**/src/**/*.mp3',
        '**/src/**/*.css',
        '**/src/**/*.webp',
        '**/src/icons/**',
        '**/assets/icons/**',
        '**/src/api/**',
        '**/src/assets/**',
        '**/src/config/**',
        '**/src/contexts/**',
        '**/src/hooks/**',
        '**/src/icons/**',
        '**/src/libs/**',
        '**/src/locales/**',
        '**/src/routes/**',
        '**/src/slices/**',
        '**/src/stores/**',
        '**/src/stories/**',
        '**/src/tests/**',
        '**/src/theme/**',
        '**/src/thunks/**',
        '**/src/types/**',
        '**/src/utils/**',
      ],
      include: [
        '**/src/features/**',
        '**/src/pages/**',
        '**/src/components/**',
        '**/src/layouts/**',
      ],
      coverage: {
        exclude: [
          '**/node_modules/**',
          '**/dist/**',
          '**/cypress/**',
          '**/.{idea,git,cache,output,temp}/**',
          '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
          '**/electron/**',
          '**/html/**',
          '**/out/**',
          '**/mock/**',
          '**/src/libs/**',
          '**/src/**/*.backup.ts',
          '**/src/**/*.lib.ts',
          '**/src/**/*.backup.tsx',
          '**/src/**/*.lib.tsx',
          '**/src/**/*.backup',
          '**/src/**/*.lib',
          '**/src/**/lib/**',
          '**/src/**/*.ts',
          '**/src/**/*.js',
          '**/src/**/*.png',
          '**/src/**/*.svg',
          '**/src/**/*.mp3',
          '**/src/**/*.css',
          '**/src/**/*.webp',
          '**/src/icons/**',
          '**/assets/icons/**',
          '**/src/api/**',
          '**/src/assets/**',
          '**/src/config/**',
          '**/src/contexts/**',
          '**/src/hooks/**',
          '**/src/icons/**',
          '**/src/libs/**',
          '**/src/locales/**',
          '**/src/routes/**',
          '**/src/slices/**',
          '**/src/stores/**',
          '**/src/stories/**',
          '**/src/tests/**',
          '**/src/theme/**',
          '**/src/thunks/**',
          '**/src/types/**',
          '**/src/utils/**',
        ],
        include: [
          '**/src/features/**',
          '**/src/pages/**',
          '**/src/components/**',
          '**/src/layouts/**',
        ],
        reportOnFailure: true,
      },
      logHeapUsage: true,
      alias: [{ find: 'react-winbox', replacement: 'winbox/src/js/winbox.js' }],
    },
    resolve: {
      alias: [{ find: '@test', replacement: path.join(process.cwd(), 'src/tests') }],
    },
  })
);
